server:
  port: 8081
spring:
  application:
    name: sanri-tools
  profiles:
    active: company
  main:
    banner-mode: "off"
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
data:
  path:
    config: d:/test/config
    tmp: d:/tmp
translate:
  baidu:
    appId: appid
    secret: secret
  youdao:
    appId: appKey
    secret: appSecret