server:
  port: 8081
spring:
  application:
    name: sanri-tools
  profiles:
    active: company
  main:
    banner-mode: "off"
  freemarker:
    cache: false
data:
  path:
    config: d:/test/config
    tmp: d:/tmp