### 获取所有连接
GET {{baseUrl}}/sqlclient/connections

### 获取连接信息
GET {{baseUrl}}/sqlclient/connectionInfo?name=localhost

### 获取连接的所有 schema
GET {{baseUrl}}/sqlclient/schemas?connName=localhost

### 获取所有表
GET {{baseUrl}}/sqlclient/tables?connName=localhost&schemaName=shiro_demo

### 获取表字段列表
GET {{baseUrl}}/sqlclient/refreshTable?connName=localhost&schemaName=shiro_demo&tableName=sys_user

### 加载所有表关系
GET {{baseUrl}}/sqlclient/loadTableRelations?connName=localhost&schemaName=shiro_demo&tableName=sys_role

### 配置表关系
POST {{baseUrl}}/sqlclient/configTableRelation
Content-Type: application/json

{"tableRelationParam":{
  "connName": "localhost",
  "schemaName": "shiro_demo",
  "sourceTableName": "sys_user",
  "targetTableName": "sys_role",
  "sourceColumnName": "id",
  "targetColumnName": "id",
  "relation": "MANY_MANY"
}}

### 类加载器-上传一个打包类
POST {{baseUrl}}/classloader/uploadClasses
Content-Type: multipart/form-data; boundary=37c2bf7cd94d4a4b89c60130b045f7aa

--37c2bf7cd94d4a4b89c60130b045f7aa
Content-Disposition: form-data; name="fileItem"; filename="test.zip"
Content-Type: application/octet-stream

--37c2bf7cd94d4a4b89c60130b045f7aa
Content-Type: application/x-www-form-urlencoded

title=testXXX

< d:/test/test.zip

### 类加载器-列出所有的类加载器
GET {{baseUrl}}/classloader/classloaders

### 类加载器-列出加载的类
GET {{baseUrl}}/classloader/loadedClasses?name=abc

### redis-查看所有的连接列表
GET {{baseUrl}}//file/manager/simpleConfigNames?modul=redis

### redis-加载出数据
GET {{baseUrl}}/redis/data?connName=localhost&key=sanri&serializable=jdk&classloaderName=abc

### redis-写入 redis 连接信息
POST {{baseUrl}}/file/manager/writeConfig
Content-Type: application/x-www-form-urlencoded

modul=redis&baseName=localhost&content={"connectStrings":"localhost:6379"}

### redis-获取 redis 节点数据
GET {{baseUrl}}/redis/redisNodes?connName=company

### redis-查询某个 key
GET {{baseUrl}}/redis/scan?connName=company&pattern=*AUTH:sso_user*&limit=10

### 随机数据-随机列表数据
GET {{baseUrl}}/random/randomListData?className=com.sanri.test.testredis.dto.NormalObject&classloaderName=Normal-test.zip-loader

###